### ISSUE TITLE
Please document the format of input images

### ISSUE THREAD

**Issue by jsbien** [impactcentre/inventory-extraction#2]
What is "the segmentation tools created by NCSR within the IMPACT project"?
Google is unable to find anything on "the Im2CharRects tool of IBM" - an aborted project?

**Comment by jkloe** [comment]
- As far as I remember, the NCSR segementation tools were line / word / character  segmentations of document images. But they were never freely available
- the Im2CharRects tool of IBM was part of an aborted project, yes

**Comment by jkloe** [comment]
The best viable way to use the tool is to use the character segmentations provided by ABBYY OCR XMLs

**Comment by jsbien** [comment]
I understand ABBY OCR is used internally by Transkribus, but XML is not available for export (legal limitations I guess). Are you aware of any reliable converter to ABBY XML from PAGE or hOCR?

**Comment by jkloe** [comment]
Unfortunately no, I am not aware of such a tool.
